### ISSUE TITLE
Cannot extend L.Control.Geocoder since version 2.0.0

### ISSUE THREAD

**Issue by bagage** [perliedman/leaflet-control-geocoder#324]
Previously we could extend Geocoder using `ExtendedGeocoder = L.Control.Geocoder.extend({})` but it seems it doesn't work anymore:

> Uncaught TypeError: L.Control.Geocoder.extend is not a function

Here is a [demo](https://codepen.io/bqg/pen/eYBQabO) of the issue (it works in 1.13.0, it doesn't in 2.X.X). 

Am I doing something wrong? Nonetheless thanks for the great library!
